import pandas as pd

# ============================================================
# REQUIRED HEVY CSV COLUMNS
# ============================================================
REQUIRED_COLUMNS = {
    "title",
    "start_time",
    "end_time",
    "description",
    "exercise_title",
    "superset_id",
    "exercise_notes",
    "set_index",
    "set_type",
    "weight_kg",
    "reps",
    "distance_km",
    "duration_seconds",
    "rpe",
}

# ============================================================
# COLUMNS TO CLEAN
# ============================================================
TEXT_COLUMNS = [
    "title",
    "description",
    "exercise_title",
    "exercise_notes",
    "set_type",
    "superset_id",
]

NUMERIC_COLUMNS = [
    "set_index",
    "weight_kg",
    "reps",
    "distance_km",
    "duration_seconds",
    "rpe",
]

# ============================================================
# STEP 1 — LOAD HEVY CSV
# ============================================================
def load_hevy_csv(path):
    """
    Path (str): Path to the exported Hevy CSV.
    Returns: pandas.DataFrame
    """

    df = pd.read_csv(path)
    return df

# ============================================================
# STEP 2 — VALIDATE CSV COLUMNS
# ============================================================
def validate_columns(df):
    """
    Ensures that all required Hevy columns exist.
    """

    missing_columns = REQUIRED_COLUMNS - set(df.columns)

    if missing_columns:
        raise ValueError(
            f"Missing required columns: {sorted(missing_columns)}"
        )

# ============================================================
# STEP 3 — CLEAN DATAFRAME
# ============================================================
def clean_dataframe(df):
    """
    Cleans and standardizes the Hevy DataFrame.
    """

    # Work on a copy so the original DataFrame is unchanged
    df = df.copy()

    for column in TEXT_COLUMNS:
        df[column] = (
            df[column]
            .fillna("")
            .astype(str)
            .str.strip()
            .replace("", None)
        )

    for column in NUMERIC_COLUMNS:
        df[column] = pd.to_numeric(
            df[column],
            errors="coerce"
        )

    df["start_time"] = pd.to_datetime(df["start_time"]).dt.strftime("%Y-%m-%d %H:%M:%S")

    df["end_time"] = pd.to_datetime(df["end_time"]).dt.strftime("%Y-%m-%d %H:%M:%S")

    return df

# ============================================================
# STEP 4A — GET OR CREATE EXERCISE
# ============================================================
def get_or_create_exercise(conn, exercise_name):
    """
    Returns the exercise_id for an exercise.
    """

    cursor = conn.cursor()

    # Check whether exercise already exists
    cursor.execute(
        """
        SELECT exercise_id
        FROM exercises
        WHERE name = ?
        """,
        (exercise_name,)
    )

    result = cursor.fetchone()

    # Exercise already exists
    if result:
        return result[0]

    # Exercise does not exist, so create it
    cursor.execute(
        """
        INSERT INTO exercises(name)
        VALUES(?)
        """,
        (exercise_name,)
    )

    # Return ID generated by SQLite
    return cursor.lastrowid

# ============================================================
# STEP 4B — GET OR CREATE SESSION
# ============================================================
def get_or_create_session(
    conn,
    start_time,
    title,
    end_time,
    description
):
    """
    Returns the session_id and whether the session is new.

    If the session already exists:
        returns (existing_session_id, False)

    If the session does not exist:
        creates it and returns (new_session_id, True)
    """
    cursor = conn.cursor()

    cursor.execute(
        """
        SELECT session_id
        FROM workout_sessions
        WHERE hevy_session_key = ?
        """,
        (start_time,)
    )

    result = cursor.fetchone()

    # Session already exists
    if result:
        return result[0], False

    # Session does not exist, so create it
    cursor.execute(
        """
        INSERT INTO workout_sessions (
            hevy_session_key,
            title,
            start_time,
            end_time,
            description
        )
        VALUES (?, ?, ?, ?, ?)
        """,
        (
            start_time,
            title,
            start_time,
            end_time,
            description
        )
    )

    # Return new ID and True because this is a new session
    return cursor.lastrowid, True

# ============================================================
# STEP 4C — INSERT WORKOUT SET
# ============================================================

def insert_workout_set(
    conn,
    session_id,
    exercise_id,
    order_in_session,
    set_number,
    set_type,
    weight,
    reps,
    distance_km,
    duration_seconds,
    superset_id,
    exercise_notes,
    rpe
):
    """
    Inserts one workout set into workout_sets.
    """

    cursor = conn.cursor()

    cursor.execute(
        """
        INSERT INTO workout_sets (
            session_id,
            exercise_id,
            order_in_session,
            set_number,
            set_type,
            weight,
            reps,
            distance_km,
            duration_seconds,
            superset_id,
            exercise_notes,
            rpe
        )
        VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
        """,
        (
            session_id,
            exercise_id,
            order_in_session,
            set_number,
            set_type,
            weight,
            reps,
            distance_km,
            duration_seconds,
            superset_id,
            exercise_notes,
            rpe
        )
    )

def import_hevy_csv(path, conn):
    """
    Imports a Hevy CSV file into the RepWise SQLite database.

    Each workout session is handled as a separate transaction.
    If a session fails, only that session is rolled back.
    Previously successful sessions remain imported.
    """

    df = load_hevy_csv(path)

    validate_columns(df)

    df = clean_dataframe(df)

    df = df.sort_values(by=["start_time"]).reset_index(drop=True)

    for start_time, session_df in df.groupby(
        "start_time",
        sort=True
    ):

        try:
            # Start a transaction for this workout
            conn.execute("BEGIN")

            # ------------------------------------------------
            # Get session information
            # ------------------------------------------------
            first_row = session_df.iloc[0]

            session_id, is_new= get_or_create_session(
                conn=conn,
                start_time=start_time,
                title=first_row["title"],
                end_time=first_row["end_time"],
                description=first_row["description"]
            )

            if not is_new:
                conn.rollback()
                print(f"Skipping already imported workout: {start_time}")
                continue

            # ------------------------------------------------
            # Insert each set in this workout
            # ------------------------------------------------

            for order_in_session, (_, row) in enumerate(
                session_df.iterrows(),
                start=1
            ):

                # Get or create exercise
                exercise_id = get_or_create_exercise(
                    conn,
                    row["exercise_title"]
                )

                # Insert workout set
                insert_workout_set(
                    conn=conn,
                    session_id=session_id,
                    exercise_id=exercise_id,
                    order_in_session=order_in_session,
                    set_number=row["set_index"],
                    set_type=row["set_type"],
                    weight=row["weight_kg"],
                    reps=row["reps"],
                    distance_km=row["distance_km"],
                    duration_seconds=row["duration_seconds"],
                    superset_id=row["superset_id"],
                    exercise_notes=row["exercise_notes"],
                    rpe=row["rpe"]
                )

            # ------------------------------------------------
            # Everything for this session succeeded
            # ------------------------------------------------

            conn.commit()

            print(
                f"Imported workout: {start_time}"
            )

        except Exception as e:

            # Something went wrong with this workout
            conn.rollback()

            print(
                f"Failed to import workout: {start_time}"
            )
            print(f"Reason: {e}")